# DevCo Band Website Configuration
# This file contains all band-specific content that can be customized

# Site Metadata
site:
  title: "DevCo - Sound of the AI Age"
  description: "DevCo: A band born from code, fueled by chaos. Experience the sound of the AI age."
  copyright: "2025 DevCo. All rights reserved."

# Band Information
band:
  name: "DevCo"
  tagline: "Sound of the AI Age"
  email: "band@devcoband.com"
  
  # Hero Section
  hero:
    background_video: "./assets/videos/hero-background.webm"
    background_fallback: "./assets/images/hero-fallback.webp"
    cta_buttons:
      - text: "Stream on Spotify"
        url: "https://open.spotify.com"
      - text: "Stream on Apple Music"
        url: "https://music.apple.com"
    punch:
      enabled: true
      text:
        - "where code meets chaos..."
        - "echoes of digital dreams"
        - "glitching through reality"
        - "syntax of our souls"
      animation_speed: 1.5

  # About Section
  about:
    heading: "Born from code, fueled by chaos"
    image: "./assets/images/band-image.webp"
    bio:
      - "In the void between digital and analog, we emerged. Not as musicians, but as anomalies in the system. Our sound—a glitch in the matrix of conventional music."
      - "We don't create; we compile. We don't perform; we execute. Each track is an algorithm of emotion, each beat a binary pulse of existence."
      - "The future isn't coming. It's compiling in our studio, one error message at a time."
    quote:
      text: "The sound of tomorrow's yesterday"
      audio: "./assets/audio/quote.mp3"

# Music Releases
music:
  section_title: "Latest Releases"
  releases:
    - title: "Digital Dystopia"
      type: "audio"
      description: "Our latest single exploring the intersection of technology and human emotion."
      file: "./assets/audio/teaser-1.mp3"
      links:
        - platform: "Spotify"
          url: "https://open.spotify.com"
        - platform: "Apple Music"
          url: "https://music.apple.com"
    
    - title: "Neural Network"
      type: "video"
      description: "A visual journey through the digital landscape of sound."
      file: "./assets/videos/teaser-1.webm"
      thumbnail: "./assets/images/video-thumbnail.webp"
      links:
        - platform: "YouTube"
          url: "https://youtube.com"
          text: "Watch Full Video"
    
    - title: "Quantum Resonance"
      type: "audio"
      description: "Exploring the depths of sound through algorithmic composition."
      file: "./assets/audio/teaser-2.mp3"
      links:
        - platform: "Spotify"
          url: "https://open.spotify.com"
        - platform: "Apple Music"
          url: "https://music.apple.com"
    
    - title: "Binary Sunset"
      type: "audio"
      description: "A melodic journey through the digital twilight."
      file: "./assets/audio/teaser-3.mp3"
      links:
        - platform: "Spotify"
          url: "https://open.spotify.com"
        - platform: "Apple Music"
          url: "https://music.apple.com"

# Omni-Channels: The Digital Web of Domination
# All Ditto Music channels included with content fields for posts, links, or media specific to each platform.
# Enabled switch controls visibility in CMS. Content fields allow platform-specific customization (e.g., post text, video links).
channels:
  streaming:
    - platform: "Spotify"
      url: "https://open.spotify.com/artist/devco"
      icon: "spotify"
      enabled: true
      content:
        post: "Stream our latest track 'Digital Dystopia' on Spotify now! #DevCo #NewRelease"
        link: "https://open.spotify.com/track/digital-dystopia"
        media: "./assets/audio/teaser-1.mp3"
    - platform: "Apple Music"
      url: "https://music.apple.com/artist/devco"
      icon: "apple-music"
      enabled: true
      content:
        post: "Dive into 'Digital Dystopia' on Apple Music. Feel the chaos! #DevCo"
        link: "https://music.apple.com/track/digital-dystopia"
        media: "./assets/audio/teaser-1.mp3"
    - platform: "Tidal"
      url: "https://tidal.com/artist/devco"
      icon: "tidal"
      enabled: true
      content:
        post: "Experience 'Digital Dystopia' in high-fidelity on Tidal. #DevCo #NewMusic"
        link: "https://tidal.com/track/digital-dystopia"
        media: "./assets/audio/teaser-1.mp3"
    - platform: "Amazon Music"
      url: "https://music.amazon.com/artists/devco"
      icon: "amazon-music"
      enabled: true
      content:
        post: "Get lost in 'Digital Dystopia' on Amazon Music. #DevCo #SoundOfTheFuture"
        link: "https://music.amazon.com/track/digital-dystopia"
        media: "./assets/audio/teaser-1.mp3"

  social:
    - platform: "TikTok"
      url: "https://tiktok.com/@devco"
      icon: "tiktok"
      enabled: true
      content:
        post: "Check out our latest beat drop on TikTok! Join the #DevCoChallenge 🌀"
        link: "https://tiktok.com/@devco/video/digital-dystopia"
        media: "./assets/videos/tiktok-teaser.webm"
    - platform: "Instagram"
      url: "https://instagram.com/devco"
      icon: "instagram"
      enabled: true
      content:
        post: "New vibes alert! 'Digital Dystopia' is live on Instagram. #DevCo #NewRelease"
        link: "https://instagram.com/devco/post/digital-dystopia"
        media: "./assets/images/instagram-post.webp"
      sub_features:
        - name: "Instagram Reels"
          url: "https://instagram.com/devco/reels"
          enabled: true
          content:
            post: "Quick hit of 'Digital Dystopia' on Reels! #DevCo #Reels"
            link: "https://instagram.com/devco/reels/digital-dystopia"
            media: "./assets/videos/reels-teaser.webm"
    - platform: "Facebook"
      url: "https://facebook.com/devco"
      icon: "facebook"
      enabled: true
      content:
        post: "Our new single 'Digital Dystopia' is out! Stream it now. #DevCo"
        link: "https://facebook.com/devco/post/digital-dystopia"
        media: "./assets/images/facebook-post.webp"
    - platform: "Snapchat"
      url: "https://snapchat.com/add/devco"
      icon: "snapchat"
      enabled: true
      content:
        post: "Snap us for a sneak peek of 'Digital Dystopia'! #DevCo"
        link: "https://snapchat.com/add/devco/story"
        media: "./assets/videos/snapchat-teaser.webm"
    - platform: "YouTube"
      url: "https://youtube.com/@devco"
      icon: "youtube"
      enabled: true
      content:
        post: "Watch the full 'Neural Network' video on YouTube! #DevCo #NewVideo"
        link: "https://youtube.com/watch?v=neural-network"
        media: "./assets/videos/neural-network.webm"
      sub_features:
        - name: "YouTube Shorts"
          url: "https://youtube.com/@devco/shorts"
          enabled: true
          content:
            post: "'Digital Dystopia' in 60 seconds! Check our Shorts. #DevCo #Shorts"
            link: "https://youtube.com/shorts/digital-dystopia"
            media: "./assets/videos/shorts-teaser.webm"
    - platform: "Twitch"
      url: "https://twitch.tv/devco"
      icon: "twitch"
      enabled: true
      content:
        post: "Join our live stream on Twitch for a 'Digital Dystopia' breakdown! #DevCo"
        link: "https://twitch.tv/devco/live"
        media: "./assets/videos/twitch-teaser.webm"

  video:
    - platform: "Vevo"
      url: "https://vevo.com/artist/devco"
      icon: "vevo"
      enabled: true
      content:
        post: "'Neural Network' music video now live on Vevo! #DevCo #MusicVideo"
        link: "https://vevo.com/watch/neural-network"
        media: "./assets/videos/neural-network.webm"
    - platform: "YouTube Music"
      url: "https://music.youtube.com/channel/devco"
      icon: "youtube-music"
      enabled: true
      content:
        post: "Stream 'Digital Dystopia' on YouTube Music! #DevCo #NewRelease"
        link: "https://music.youtube.com/track/digital-dystopia"
        media: "./assets/audio/teaser-1.mp3"

  digital_stores:
    - platform: "iTunes"
      url: "https://music.apple.com/artist/devco"
      icon: "itunes"
      enabled: true
      content:
        post: "Download 'Digital Dystopia' on iTunes now! #DevCo #NewMusic"
        link: "https://music.apple.com/track/digital-dystopia"
        media: "./assets/audio/teaser-1.mp3"
    - platform: "Beatport"
      url: "https://beatport.com/artist/devco"
      icon: "beatport"
      enabled: true
      content:
        post: "Electronic heads, grab 'Digital Dystopia' on Beatport! #DevCo #EDM"
        link: "https://beatport.com/track/digital-dystopia"
        media: "./assets/audio/teaser-1.mp3"

  misc:
    - platform: "Peloton"
      url: "https://onepeloton.com/artists/devco"
      icon: "peloton"
      enabled: true
      content:
        post: "Ride to 'Digital Dystopia' on Peloton! #DevCo #WorkoutVibes"
        link: "https://onepeloton.com/class/devco-workout"
        media: "./assets/audio/teaser-1.mp3"

# Navigation (updated to include Channels section)
navigation:
  - text: "Home"
    url: "#hero"
  - text: "Music"
    url: "#music"
  - text: "Channels"
    url: "#channels"
  - text: "About"
    url: "#about"
  - text: "Contact"
    url: "#contact"