# DevCo Band Website Configuration
# This file contains all band-specific content that can be customized

# Site Metadata
site:
  title: "DevCo - Sound of the AI Age"
  description: "DevCo: A band born from code, fueled by chaos. Experience the sound of the AI age."
  copyright: "2025 DevCo. All rights reserved."

# Band Information
band:
  name: "DevCo"
  tagline: "Sound of the AI Age"
  email: "band@devcoband.com"
  
  # Hero Section
  hero:
    background_video: "./assets/videos/hero-background.webm"
    background_fallback: "./assets/images/hero-fallback.webp"
    cta_buttons:
      - text: "DevCo Radio on Spotify"
        url: "https://open.spotify.com/playlist/37i9dQZF1E4xtx4CyH5mze?si=3CdxyHt-TCaCT7Jot7ljGw&nd=1&dlsi=0a6ba9739add4516"
    punch:
      enabled: true
      text:
        - "where code meets chaos..."
        - "echoes of digital dreams"
        - "glitching through reality"
        - "syntax of our souls"
      animation_speed: 1.5

  # About Section
  about:
    heading: "Born from code, fueled by chaos"
    image: "./assets/images/band-image.webp"
    bio:
      - "In the void between digital and analog, we emerged. Not as musicians, but as anomalies in the system. Our sound—a glitch in the matrix of conventional music."
      - "We don't create; we compile. We don't perform; we execute. Each track is an algorithm of emotion, each beat a binary pulse of existence."
      - "The future isn't coming. It's compiling in our studio, one error message at a time."
    quote:
      text: "The sound of tomorrow's yesterday"
      audio: "./assets/audio/quote.mp3"

# Music Releases
music:
  section_title: "Latest Releases"
  releases:
    - title: "Second Love"
      type: "video"
      featured: true
      description: "Our debut video exploring themes of connection in a digital age."
      file: "./assets/videos/teaser-1.webm"
      thumbnail: "./assets/images/second_love.png"
      links:
        - platform: "YouTube"
          url: "https://youtu.be/y6Vm1pl_pwE?si=ZnrphstxSX_2ATaI"
          text: "Watch Full Video"
    
    - title: "Pop Song Summer"
      type: "audio"
      featured: false
      description: "Our latest single exploring the intersection of technology and human emotion."
      file: "./assets/audio/teaser-1.mp3"
      links:
        - platform: "Spotify"
          url: "https://open.spotify.com/track/4jCgwrDW7OgTbbD9zfwSRn"
    

# Omni-Channels: The Digital Web of Domination
# All Ditto Music channels included with content fields for posts, links, or media specific to each platform.
# Enabled switch controls visibility in CMS. Content fields allow platform-specific customization (e.g., post text, video links).
channels:
  streaming:
    - platform: "Spotify"
      url: "https://open.spotify.com/playlist/37i9dQZF1E4xtx4CyH5mze?si=3CdxyHt-TCaCT7Jot7ljGw&nd=1&dlsi=0a6ba9739add4516"
      icon: "spotify"
      enabled: true
      content:
        post: "Our full discography is available on Spotify, including our latest single 'Pop Song Summer'. #DevCo #NewRelease"
        link: "https://open.spotify.com/track/4jCgwrDW7OgTbbD9zfwSRn"
        media: "./assets/audio/teaser-1.mp3"
      description: "Our full discography is available on Spotify, including our latest single 'Pop Song Summer'."
    - platform: "SoundCloud"
      url: "https://soundcloud.com/devco-music"
      icon: "soundcloud"
      enabled: true
      content:
        post: "Everything we put on Spotify also goes on SoundCloud! Check out 'Pop Song Summer' now. #DevCo"
        link: "https://soundcloud.com/devco-music"
        media: "./assets/audio/teaser-1.mp3"
    - platform: "Tidal"
      url: "https://tidal.com/artist/devco"
      icon: "tidal"
      enabled: true
      content:
        post: "Experience 'Pop Song Summer' in high-fidelity on Tidal. #DevCo #NewMusic"
        link: "https://tidal.com/track/pop-song-summer"
        media: "./assets/audio/teaser-1.mp3"
    - platform: "Amazon Music"
      url: "https://music.amazon.com/artists/devco"
      icon: "amazon-music"
      enabled: true
      content:
        post: "Get lost in 'Pop Song Summer' on Amazon Music. #DevCo #SoundOfTheFuture"
        link: "https://music.amazon.com/track/pop-song-summer"
        media: "./assets/audio/teaser-1.mp3"

  social:
    - platform: "Facebook"
      url: "https://www.facebook.com/profile.php?id=61579902307562"
      icon: "facebook"
      enabled: true
      content:
        post: "Come for the art, stay for the music, follow for the story. We share exclusive art and music ahead of release. #DevCo"
        link: "https://www.facebook.com/profile.php?id=61579902307562"
        media: "./assets/images/facebook-post.webp"
      description: "Come for the art, stay for the music, follow for the story. We share exclusive art and music ahead of release."
    - platform: "YouTube"
      url: "https://www.youtube.com/watch?v=y6Vm1pl_pwE&list=PLsXH35TcNO8Kcqt6Yqd7-saAOVc0QWEA6"
      icon: "youtube"
      enabled: true
      content:
        post: "Longer videos of full songs - some will make the album, others are exclusive bonus tracks you won't find elsewhere. #DevCo"
        link: "https://www.youtube.com/watch?v=y6Vm1pl_pwE&list=PLsXH35TcNO8Kcqt6Yqd7-saAOVc0QWEA6"
        media: "./assets/images/second_love.png"
      description: "Longer videos of full songs - some will make the album, others are exclusive bonus tracks you won't find elsewhere."
    - platform: "Twitter/X"
      url: "https://x.com/DevCoBand"
      icon: "twitter"
      enabled: true
      content:
        post: "We follow and promote other artists, focusing exclusively on music, art, and short stories - no politics, just creativity. #DevCo"
        link: "https://x.com/DevCoBand"
        media: "./assets/images/twitter-post.webp"
      description: "We follow and promote other artists, focusing exclusively on music, art, and short stories - no politics, just creativity."
    
    - platform: "SoundCloud"
      url: "https://soundcloud.com/devco-music"
      icon: "soundcloud"
      enabled: true
      content:
        post: "Everything we put on Spotify also goes on SoundCloud - an alternative way to stream our music. #DevCo"
        link: "https://soundcloud.com/devco-music"
        media: "./assets/audio/teaser-1.mp3"
      description: "Everything we put on Spotify also goes on SoundCloud - an alternative way to stream our music."

  video:
    - platform: "Vevo"
      url: "https://vevo.com/artist/devco"
      icon: "vevo"
      enabled: true
      content:
        post: "'Second Love' music video now live on Vevo! #DevCo #MusicVideo"
        link: "https://vevo.com/watch/second-love"
        media: "./assets/images/second_love.png"
    - platform: "YouTube Music"
      url: "https://music.youtube.com/channel/devco"
      icon: "youtube-music"
      enabled: true
      content:
        post: "Stream 'Pop Song Summer' on YouTube Music! #DevCo #NewRelease"
        link: "https://music.youtube.com/track/pop-song-summer"
        media: "./assets/audio/teaser-1.mp3"

  digital_stores:
    - platform: "Beatport"
      url: "https://beatport.com/artist/devco"
      icon: "beatport"
      enabled: true
      content:
        post: "Electronic heads, grab 'Pop Song Summer' on Beatport! #DevCo #EDM"
        link: "https://beatport.com/track/pop-song-summer"
        media: "./assets/audio/teaser-1.mp3"

  misc:
    - platform: "Peloton"
      url: "https://onepeloton.com/artists/devco"
      icon: "peloton"
      enabled: true
      content:
        post: "Ride to 'Pop Song Summer' on Peloton! #DevCo #WorkoutVibes"
        link: "https://onepeloton.com/class/devco-workout"
        media: "./assets/audio/teaser-1.mp3"

# Navigation (updated to include Channels section)
navigation:
  - text: "Home"
    url: "#hero"
  - text: "Music"
    url: "#music"
  - text: "Channels"
    url: "#channels"
  - text: "About"
    url: "#about"
  - text: "Contact"
    url: "#contact"